version: "3.9"

services:
  mysql:
    image: mysql:8
    # build:
    #   context: .
    #   dockerfile: MySQLDockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=test_user
      - MYSQL_DATABASE=employees_db
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
